In [1]:
import copy
import numpy as np
from open3d import *

In [2]:
print("Testing mesh in Open3d")
mesh = read_triangle_mesh("knot.ply")
print(mesh)
print(np.asarray(mesh.vertices))
print(np.asarray(mesh.triangles))

Testing mesh in Open3d
TriangleMesh with 1440 points and 2880 triangles.
[[  4.51268387  28.68865967 -76.55680847]
 [  7.63622284  35.52046967 -69.78063965]
 [  6.21986008  44.22465134 -64.82303619]
 ...
 [-22.12651634  31.28466606 -87.37570953]
 [-13.91188431  25.4865818  -86.25827026]
 [ -5.27768707  23.36245346 -81.43279266]]
[[   0   12   13]
 [   0   13    1]
 [   1   13   14]
 ...
 [1438   11 1439]
 [1439   11    0]
 [1439    0 1428]]


In [3]:
 print("Try to render a mesh with normals (exist: " +
            str(mesh.has_vertex_normals()) +
            ") and colors (exist: " + str(mesh.has_vertex_colors()) + ")")

Try to render a mesh with normals (exist: False) and colors (exist: False)


In [4]:
draw_geometries([mesh])

In [6]:
print("Computeing normal and rendering it")
mesh.compute_vertex_normals()
print(np.asarray(mesh.triangle_normals))
draw_geometries([mesh])

Computeing normal and rendering it
[[ 0.79164373 -0.53951444  0.28674793]
 [ 0.8319824  -0.53303008  0.15389681]
 [ 0.83488162 -0.09250101  0.54260136]
 ...
 [ 0.16269924 -0.76215917 -0.6266118 ]
 [ 0.52755226 -0.83707495 -0.14489352]
 [ 0.56778973 -0.76467734 -0.30476777]]


In [8]:
print("We make a partial mesh of only the first half triangles")
mesh1 = copy.deepcopy(mesh)
mesh1.triangles = Vector3iVector(np.asarray(mesh1.triangles)[:len(mesh1.triangles)//2, :])
mesh1.triangle_normals = Vector3dVector(np.asarray(mesh1.triangle_normals)[:len(mesh1.triangle_normals)//2, :])

We make a partial mesh of only the first half triangles


In [9]:
print(mesh1.triangles)

std::vector<Eigen::Vector3i> with 1440 elements.
Use numpy.asarray() to access data.


In [10]:
draw_geometries([mesh1])

In [13]:
print("Painting the mesh")
mesh1.paint_uniform_color([1, 0.706, 0])
draw_geometries([mesh1])

Painting the mesh
